name: Metrics
on:
  schedule: [{cron: "0 2 * * 3"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: puppetlabs
          filename: profile/github-metrics.svg
          output_action: pull-request
